// <auto-generated />
using System;
using CarShopping.Model.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarShopping.Migrations
{
    [DbContext(typeof(MySQLContext))]
    [Migration("20240218221950_AddDatabase")]
    partial class AddDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CarShopping.Model.Car", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("brand");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<DateOnly>("FabricationDate")
                        .HasColumnType("date")
                        .HasColumnName("fabricationDate");

                    b.Property<bool>("IsAvaliable")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isAvaliable");

                    b.Property<bool>("IsSold")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isSold");

                    b.Property<int>("Mileage")
                        .HasColumnType("int")
                        .HasColumnName("mileage");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<double>("SellingValue")
                        .HasColumnType("double")
                        .HasColumnName("sellingValue");

                    b.HasKey("Id");

                    b.ToTable("car");
                });

            modelBuilder.Entity("CarShopping.Model.CarDealer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<int>("AmountAvaliableCars")
                        .HasColumnType("int")
                        .HasColumnName("amountAvaliableCars");

                    b.Property<int>("CarQuantity")
                        .HasColumnType("int")
                        .HasColumnName("carQuantity");

                    b.Property<int>("Employees")
                        .HasColumnType("int")
                        .HasColumnName("employeesQuantity");

                    b.Property<double>("MonthRevenue")
                        .HasColumnType("double")
                        .HasColumnName("monthRevenue");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("dealership");
                });
#pragma warning restore 612, 618
        }
    }
}
