// <auto-generated />
using System;
using CarShopping.Model.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarShopping.Migrations
{
    [DbContext(typeof(MySQLContext))]
    [Migration("20240411162700_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarShopping.Model.Car", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("brand");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<DateTime>("FabricationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("fabricationDate");

                    b.Property<bool>("IsAvaliable")
                        .HasColumnType("bit")
                        .HasColumnName("isAvaliable");

                    b.Property<bool>("IsSold")
                        .HasColumnType("bit")
                        .HasColumnName("isSold");

                    b.Property<int>("Mileage")
                        .HasColumnType("int")
                        .HasColumnName("mileage");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<double>("SellingValue")
                        .HasColumnType("float")
                        .HasColumnName("sellingValue");

                    b.HasKey("Id");

                    b.ToTable("car");
                });

            modelBuilder.Entity("CarShopping.Model.CarDealer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AmountAvaliableCars")
                        .HasColumnType("int")
                        .HasColumnName("amountAvaliableCars");

                    b.Property<int>("CarQuantity")
                        .HasColumnType("int")
                        .HasColumnName("carQuantity");

                    b.Property<int>("Employees")
                        .HasColumnType("int")
                        .HasColumnName("employeesQuantity");

                    b.Property<double>("MonthRevenue")
                        .HasColumnType("float")
                        .HasColumnName("monthRevenue");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("dealership");
                });
#pragma warning restore 612, 618
        }
    }
}
